"""
WAF / IPS fingerprinting + tamper-chain recommendation.
Signatures are drawn from publicly documented response header/cookie/body
markers (the same kind of markers used by public tools like wafw00f) -
written independently for Anka.
"""

from core.http_client import HttpClient
from core import logger

# Each entry: name -> list of (location, needle) where location is
# 'header', 'cookie', or 'body'. Matching is case-insensitive substring.
WAF_SIGNATURES = {
    "Cloudflare": [
        ("header", "cf-ray"),
        ("header", "server: cloudflare"),
        ("cookie", "__cfduid"),
        ("body", "attention required! | cloudflare"),
    ],
    "Akamai": [
        ("header", "akamaighost"),
        ("header", "x-akamai-transformed"),
    ],
    "Imperva Incapsula": [
        ("cookie", "incap_ses"),
        ("cookie", "visid_incap"),
        ("body", "incapsula incident id"),
    ],
    "F5 BIG-IP ASM": [
        ("cookie", "ts=") ,
        ("header", "x-cnection"),
        ("body", "the requested url was rejected"),
    ],
    "Sucuri": [
        ("header", "x-sucuri-id"),
        ("header", "server: sucuri"),
        ("body", "access denied - sucuri website firewall"),
    ],
    "AWS WAF": [
        ("header", "x-amzn-requestid"),
        ("body", "request blocked. we can't connect to the server"),
    ],
    "ModSecurity": [
        ("body", "mod_security"),
        ("body", "this error was generated by mod_security"),
    ],
    "Barracuda": [
        ("cookie", "barra_counter_session"),
        ("body", "you have been blocked"),
    ],
    "Fortinet FortiWeb": [
        ("header", "fortiwafsid"),
        ("body", "fortiweb"),
    ],
    "Wordfence": [
        ("body", "generated by wordfence"),
        ("body", "your access to this site has been limited"),
    ],
    "DDoS-Guard": [
        ("header", "server: ddos-guard"),
    ],
    "StackPath": [
        ("header", "x-sp-waf-block"),
    ],
    "Azure Front Door / App Gateway WAF": [
        ("header", "x-azure-ref"),
        ("body", "the page cannot be displayed because an internal server error has occurred"),
    ],
    "Google Cloud Armor": [
        ("header", "x-goog-"),
        ("body", "your client does not have permission to get url"),
    ],
    "Radware AppWall": [
        ("cookie", "rdwr"),
        ("body", "unauthorized activity has been detected"),
    ],
    "Fastly": [
        ("header", "x-served-by"),
        ("header", "fastly-"),
    ],
    "Citrix NetScaler AppFirewall": [
        ("cookie", "ns_af"),
        ("cookie", "citrix_ns_id"),
    ],
    "PerimeterX / HUMAN": [
        ("cookie", "_px"),
        ("body", "please verify you are a human"),
    ],
    "Reblaze": [
        ("cookie", "rbzid"),
        ("header", "server: reblaze"),
    ],
    "Palo Alto Networks": [
        ("body", "application blocked by palo alto networks"),
    ],
    "Signal Sciences": [
        ("header", "x-sigsci-tags"),
    ],
}

# Suggested tamper chains keyed by WAF vendor. These are generic evasion
# strategies (encoding/case/whitespace transforms) not vendor-specific
# exploits.
BYPASS_STRATEGIES = {
    "Cloudflare": ["space2comment", "randomcase", "charencode"],
    "Akamai": ["space2comment", "versionedcomments"],
    "Imperva Incapsula": ["charencode", "apostrophemask", "randomcase"],
    "F5 BIG-IP ASM": ["space2comment", "equaltolike"],
    "Sucuri": ["randomcase", "space2comment"],
    "AWS WAF": ["charencode", "unionalltrick"],
    "ModSecurity": ["versionedcomments", "space2comment", "randomcase"],
    "Barracuda": ["space2comment", "equaltolike"],
    "Fortinet FortiWeb": ["randomcase", "charencode"],
    "Wordfence": ["space2comment", "apostrophemask"],
    "DDoS-Guard": ["spacetoplus", "randomcase"],
    "StackPath": ["charencode", "space2comment"],
    "Azure Front Door / App Gateway WAF": ["charencode", "space2comment", "randomcase"],
    "Google Cloud Armor": ["doubleurlencode", "randomcase"],
    "Radware AppWall": ["space2comment", "keywordreplace"],
    "Fastly": ["spacetoplus", "charencode"],
    "Citrix NetScaler AppFirewall": ["commentsplit", "randomcase"],
    "PerimeterX / HUMAN": ["randomcase", "unicodeescape"],
    "Reblaze": ["doubleurlencode", "commentsplit"],
    "Palo Alto Networks": ["space2comment", "versionedcomments"],
    "Signal Sciences": ["charencode", "keywordreplace"],
    "unknown": ["space2comment", "randomcase"],
}

# A payload that is likely to be flagged by most WAFs, used purely to
# provoke a block page for fingerprinting purposes.
PROBE_PAYLOAD = "' OR 1=1 UNION SELECT NULL,NULL-- -"


def _matches(resp, location, needle):
    needle = needle.lower()
    if location == "header":
        header_blob = " ".join(f"{k}: {v}" for k, v in resp.headers.items()).lower()
        return needle in header_blob
    if location == "cookie":
        cookie_blob = " ".join(f"{k}={v}" for k, v in resp.cookies.items()).lower()
        return needle in cookie_blob
    if location == "body":
        return needle in resp.text.lower()
    return False


def detect_waf(client: HttpClient, point) -> dict:
    """
    Sends a provoking payload and checks the response against known
    WAF signatures. Returns {"detected": bool, "vendor": str|None,
    "bypass_chain": [tamper names]}.
    """
    from core.http_client import inject_value

    logger.info(f"[WAF] probing for WAF/IPS on param '{point['name']}'")
    params = inject_value(point["params"], point["name"], PROBE_PAYLOAD)
    if point["location"] == "GET":
        resp, _ = client.send("GET", point["base_url"], params=params)
    else:
        resp, _ = client.send("POST", point["base_url"], data=params)

    if resp is None:
        return {"detected": False, "vendor": None, "bypass_chain": []}

    for vendor, rules in WAF_SIGNATURES.items():
        for location, needle in rules:
            if _matches(resp, location, needle):
                chain = BYPASS_STRATEGIES.get(vendor, BYPASS_STRATEGIES["unknown"])
                logger.waf(f"WAF detected: {vendor} (matched '{needle}' in {location})")
                logger.waf(f"Suggested bypass chain: {' -> '.join(chain)}")
                return {"detected": True, "vendor": vendor, "bypass_chain": chain}

    # Generic block-page heuristics (status code / generic phrasing) when
    # no vendor signature matched but the request still appears blocked.
    if resp.status_code in (403, 406, 419, 429, 999):
        chain = BYPASS_STRATEGIES["unknown"]
        logger.waf(f"Generic firewall/block behavior detected (status {resp.status_code})")
        logger.waf(f"Suggested bypass chain: {' -> '.join(chain)}")
        return {"detected": True, "vendor": "unknown", "bypass_chain": chain}

    logger.info("[WAF] no firewall signature detected")
    return {"detected": False, "vendor": None, "bypass_chain": []}
